### ISSUE TITLE
README.md images

### ISSUE THREAD

**Issue by bioi** [tripal/tripal_analysis_expression#1]
![admin_pages](https://cloud.githubusercontent.com/assets/14822959/13010514/2d2dc7be-d170-11e5-8670-92bdded6659d.png)
![ncbi_xml_1](https://cloud.githubusercontent.com/assets/14822959/12490120/f5223ad8-c041-11e5-93ac-4692e27bf3d1.png)
![ncbi_xml_2](https://cloud.githubusercontent.com/assets/14822959/12490242/8cb8b796-c042-11e5-82dc-7a723867ea7a.png)

**Comment by bioi** [comment]
![biomaterial_xml](https://cloud.githubusercontent.com/assets/14822959/12989724/8e65f372-d0d4-11e5-9c0b-db1fe0d2d93c.png)

**Comment by MingChen0919** [comment]
![feature input](https://cloud.githubusercontent.com/assets/1262709/22209610/2500f872-e155-11e6-9f9d-b3c14e73ed27.png)
![2d heat map](https://cloud.githubusercontent.com/assets/1262709/22209619/28b5466c-e155-11e6-87cb-4eb69f973605.png)

**Comment by MingChen0919** [comment]
<img width="1175" alt="screen shot 2017-05-05 at 1 18 11 pm" src="https://cloud.githubusercontent.com/assets/1262709/25756810/22149cf4-3196-11e7-8f22-089f316297a0.png">
<img width="1094" alt="screen shot 2017-05-05 at 1 23 18 pm" src="https://cloud.githubusercontent.com/assets/1262709/25756812/23fd629e-3196-11e7-873b-4742c2c41116.png">
