### ISSUE TITLE
XML Read Error with Biomaterial Loader

### ISSUE THREAD

**Issue by jwest60** [tripal/tripal_analysis_expression#105]
![biodoc_6](https://user-images.githubusercontent.com/32902460/33441841-aaeb5142-d5c1-11e7-8d2a-818cf92488ce.png)

**Comment by bradfordcondon** [comment]
I believe this bug has already been resolved.  please update the repo (`git pull` on the master branch) and try again, let me know if that does not fix the issue.

**Comment by bradfordcondon** [comment]
confirmed resolved on latest
