### ISSUE TITLE
xml_biomaterial_parser error in release 1.0.2

### ISSUE THREAD

**Issue by jhumann** [tripal/tripal_analysis_expression#116]
We are using Tripal2 and have the expression module release 1.0.2 installed.  When I load the biomaterial, I get this error when running the drush command:
```
2017-12-01 13:38:01
Tripal Job Launcher
Running as user 'jhumann'
-------------------
There are 2 jobs queued.
Calling: xml_biomaterial_parser(/main/data/vaccinium/VaccRNAseq-FromMeg_Nov2017/biosample_result_Va.xml, 69, 1008)
call_user_func_array() expects parameter 1 to be a valid callback, function 'xml_biomaterial_parser' not found or invalid function name            [warning]
tripal_core.jobs.api.inc:502
Calling: xml_biomaterial_parser(/main/data/vaccinium/VaccRNAseq-FromMeg_Nov2017/biosample_result_Vc.xml, 13, 1009)
call_user_func_array() expects parameter 1 to be a valid callback, function 'xml_biomaterial_parser' not found or invalid function name            [warning]
tripal_core.jobs.api.inc:502
```
Any suggestions on how to resolve this would be greatly appreeciated.
Jodi

**Comment by bradfordcondon** [comment]
Hi Jodi,

I just launched a clean tripal 2 site and was not able to replicate this error.
 
can you please try deleting and re-downloading the [1.0.2](https://github.com/tripal/tripal_analysis_expression/archive/1.0.2.zip) release in the same location with the same folder name?

If that does not work, can you please check that the file `tripal_analysis_expression/includes/tripal_biomaterial_loader.inc` exists, and that line 493 begins with the below code?

 `function xml_biomaterial_parser($xml_path, $organism_id) {`

Thank you

Bradford

**Comment by bradfordcondon** [comment]
A second idea:  The module downloads as `tripal_analysis_expression-1.0.2`.  You will need to rename the folder `tripal_analysis_expression`.

**Comment by jhumann** [comment]
We got it solved.  Thanks!

**Comment by bradfordcondon** [comment]
Hi Jodi, great thanks.  Would you be willing to describe the issue and solution for people who may encounter this problem in the future?

Thank you

Bradford

**Comment by jhumann** [comment]
It ended up being a problem on our end, your code was fine.
