### ISSUE TITLE
MAGE implementation is very poor: loader reflects this

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_analysis_expression#143]
The expression loader is heavily commented out with `    //TODO: WE DONT USE THIS (BUT WE SHOULD)` in the form.

If we're going to ask the user for this information, we need to do something with it.  As it is, not only do we not allow users to view the various mage components (acquisitions, quantications, etc) but we dont even pass them in as variables into the loader, let alone do something with those variables.

An overhaul would include:

* create a parameters array to pass around instead of passing each variable 1 by 1.
* uncomment form and put input into the parameters array
* Use any passed parameters when constructing the quantification, assay, etc.

**Comment by bradfordcondon** [comment]
Consolidation of other issues: see #135

**Comment by noahcaldwell7** [comment]
No updates in over a year, closing issue.

**Comment by noahcaldwell7** [comment]
No updates in over a year, closing issue.
