### ISSUE TITLE
Should Fail Gracefully on Expression Heat Map

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal_analysis_expression#150]
When a user inputs unknown features and hit submit, the following error shows up:
```php
Notice: Undefined variable: x in tripal_analysis_expression_generate_heatmap_values() (line 454 of /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal_analysis_expression/tripal_analysis_expression/includes/feature_heatmap_form.inc).
Warning: Invalid argument supplied for foreach() in tripal_analysis_expression_generate_heatmap_values() (line 454 of /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal_analysis_expression/tripal_analysis_expression/includes/feature_heatmap_form.inc).
Notice: Undefined variable: max_id_len in tripal_analysis_expression_generate_heatmap_values() (line 461 of /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal_analysis_expression/tripal_analysis_expression/includes/feature_heatmap_form.inc).
```

To test, visit: http://160.36.205.61:8095/content/expression-visualization?heatmap_feature_uniquename=blah%2C+blah%2C+blah&op=Display+Expression+Heatmap&form_build_id=form-YrKAQzuzF1A1xnZQFVewontUIHBF9EfaPVnhqyA_srg&form_token=mZlJU0jKX124-xipLDjrjc_TH2qtu3yCgFD_lEhG2i8&form_id=feature_heatmap_form

To fix, simply test if the query returned any results before attempting to process it.

@MingChen0919 I am always afraid to mess with this code lol. Could you take a look please?

Thanks

**Comment by bradfordcondon** [comment]
looks resolved to me.
