### ISSUE TITLE
hierarchical clustering for heatmaps.

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_analysis_expression#210]
h-clustering is a requested feature for heatmaps.  This means sort the features by similar expression patterns in the different biomaterials.

I'd bet plot.ly has this as an out of the box feature, and, if not, theres a plug-in. common analysis.

**Comment by almasaeed2010** [comment]
There is an example in python (usually means there is an equivalent in JS) https://plot.ly/python/dendrogram/#plot-a-dendrogram-with-a-heatmap

**Comment by bradfordcondon** [comment]
looks to me like there is not an equivalent function.  https://github.com/plotly/plotly.js/issues/1321

**Comment by almasaeed2010** [comment]
This actually is possible now with plotly js:

https://plot.ly/~talgalili/23/_009681solid-cc476bsolid-99-e8b452dd3de084ea931663bbeb406a2c-0082cesolid-228b00so/#plot

Click on `python & R` then select Plotly.js from the dorpdown (will say JSON by default).

**Comment by bobbyscharmann** [comment]
Does that code pen demonstration dendograms and heatmaps in plotly.js exist elsewhere? It no longer seems to be available from the previously mentioned source.

**Comment by almasaeed2010** [comment]
Hello @bobbyscharmann 

I am not sure which code pen you are referring to. We currently do not support this type of heatmap in this module since we weren't able to replicate the functionality of the code that plotly provided. As you mentioned, they've also removed the JS example and I am not sure where else to find it.

Thanks!

**Comment by almasaeed2010** [comment]
Since this is marked with `wontfix`. I am gonna close it. Please let me know if you have any other questions.
