### ISSUE TITLE
biomaterial importer fails with remote files

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_analysis_expression#214]
this was a fun one.

in `run`: `$file_path = $this->arguments['files']['file_path'];` needs to be `    $file_path = $this->arguments['files'][0]['file_path'];` im guessing because we support multiple files instead of just one?

THEN, the downloaded file is in, for example, `/private/var/folders/p2/25r02fld33qdr02n_gp25_pm0000gn/T/import_1SqrgY`.  this means it loses the XML extension, which is what the importer uses to determine if it should use the flat file or xml loader.

I could have remote default to XML instead...

**Comment by almasaeed2010** [comment]
That private directory feels like an Apache security setting. We should look at the importer to see how it downloads stuff and where it tries to put the files. If it goes to private despite specifying a directory then that would be a bug with the importer since it should query for the location rather than assume it.

**Comment by bradfordcondon** [comment]
```

    if (array_key_exists('file_remote', $this->arguments['files'][0])){
      $extension = explode('.', $this->arguments['files'][0]['file_remote']);
      $extension = $extension[count($extension) - 1];
    }
    else {
      $extension = explode('.', $file_path);
      $extension = $extension[count($extension) - 1];
    }

```
this works instead.

**Comment by bradfordcondon** [comment]
regardless of where it puts it, it wont keep the file extension, which is the real issue.  Not to say your point isn't a valid one, it just doesnt have a bearing on the importer failing.

**Comment by bradfordcondon** [comment]
analysis expression loader also fails

* need to update `file` to `files` since support for multiple files.
* `      elseif ($filetype == 'col' and is_file($filepath) and preg_match($re_ext, $filepath)) {`
  - remove preg matches.  they are pointless except for the multiple file option
