### ISSUE TITLE
devseed loading results in all N/As on display

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_analysis_expression#227]
no matter what properties are selected, the values are n/a.

perhaps we dont set the value in the seeder?

![screen shot 2018-09-19 at 11 44 39 am](https://user-images.githubusercontent.com/7063154/45764777-75137a00-bc01-11e8-98c6-49b0752b3eae.png)

**Comment by noahcaldwell7** [comment]
No updates in over a year, closing issue.
