### ISSUE TITLE
[Tripal2] The Feature Expression form is on all pages by default.

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal_analysis_expression#243]
Hello,
In tripal_analysis_expression.module, the 'status' for both block is set to 1 by default.

```
  $blocks['input_features'] = array(
    'info' => t('tripal_analysis_expression features form for heatmap'),
    'status' => 1,
    'region' => 'content',
    'weight' => 24,
    'cache' => DRUPAL_NO_CACHE
);
```

Until is it configured by the admin, it actually pop up on all pages, including the configuration page.
In the tripal 3 version, it is set to 0.

While not a bug, it breaks the interface until configured, so I would like to make a pull request to set it to 0.

**Comment by bradfordcondon** [comment]
it actually looks like we have it commented out (its also set to 0)

```php
$blocks['input_features'] = [
    'info' => t('tripal_analysis_expression features form for heatmap'),
    //'status' => 0,
    'region' => 'content',
    'weight' => 24,
    'cache' => DRUPAL_NO_CACHE,
  ];

```

so maybe that would be more appropriate?  Either way a pR would be great, thank you

**Comment by almasaeed2010** [comment]
PR merged. Thanks!
