### ISSUE TITLE
Biomaterial loader: Incoherence betwen xml and flat files

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal_analysis_expression#247]
(Tripal v3 module)

Hello,
In the biomaterial loader, we can load both flat file and xml files.

In the XML files, we can use BioSample accession, and SRA accession.

In the flat file, we can load BioSample accession, SRA accession, and Bioproject accession. 
(https://github.com/tripal/tripal_analysis_expression/blob/master/tripal_biomaterial/includes/TripalImporter/tripal_biomaterial_loader_v3.inc#L774)

Any reason why the Bioproject accession is ignored in the XML file?

(The tripal v2 has the same issue)

**Comment by bradfordcondon** [comment]
No not particularly.  Shouldn't be hard to check for its existence and add it.  Do you have an XML snippet handy with the Bioproject Accession?  Give me that and I'll add it.

**Comment by mboudet** [comment]
Looking at some biosample on the ncbi, the BioProject accession seems to be actually in the "link" tag.
[Example](https://www.ncbi.nlm.nih.gov/biosample/10170505)
Interestingly, it is missing from the Acer saccharum sample xml file, even though it is available from the web page.. [here](https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN04958045).

Is the XML file format fixed? In the loader, we get some value by directly parsing the ID tag.
`   $sample_accession = $biosample->Ids->Id[0]; `
`  $unique_name = $biosample->Ids->Id[1]; `
`   $sra_accession = $biosample->Ids->Id[2]; `

But in the Shigella flexneri example above, the Sample name is not set. What happen if the parameter is not set/ set in another order in the ID field?

**Comment by bradfordcondon** [comment]
the loader does some really risky things in parsing the xml.  i've addressed some (for example https://github.com/tripal/tripal_analysis_expression/issues/216) but yeah it makes a lot of assumptions about what data is going to be where.  And the files can be unreliable.

The loader **should** be much more robust by getting a range of expected inputs and making sure the loader can handle them all.

**Comment by bradfordcondon** [comment]
for discussion heres the shigella you linked


```xml
<BioSampleSet>
	<BioSample access="public" accession="SAMN10170505" id="10170505" last_update="2018-10-03T08:07:18.070" publication_date="2018-10-03T00:00:00.000" submission_date="2018-10-03T08:06:20.840">
		<Ids>
			<Id db="BioSample" is_primary="1">SAMN10170505</Id>
			<Id db="SRA">SRS3871131</Id>
			<Id db="EDLB-CDC">PNUSAE017882</Id>
		</Ids>
		<Description>
			<Title>Shigella flexneri</Title>
			<Organism taxonomy_id="623" taxonomy_name="Shigella flexneri">
				<OrganismName>Shigella flexneri</OrganismName>
			</Organism>
		</Description>
		<Owner>
			<Name abbreviation="edlb-cdc">Centers for Disease Control and Prevention Enteric Diseases Laboratory Branch</Name>
		</Owner>
		<Models>
			<Model>Pathogen.cl</Model>
		</Models>
		<Package display_name="Pathogen: clinical or host-associated; version 1.0">Pathogen.cl.1.0</Package>
		<Attributes>
			<Attribute attribute_name="strain" display_name="strain" harmonized_name="strain">PNUSAE017882</Attribute>
			<Attribute attribute_name="isolate" display_name="isolate" harmonized_name="isolate">missing</Attribute>
			<Attribute attribute_name="isolation_source" display_name="isolation source" harmonized_name="isolation_source">missing</Attribute>
			<Attribute attribute_name="collected_by" display_name="collected by" harmonized_name="collected_by">CDC</Attribute>
			<Attribute attribute_name="collection_date" display_name="collection date" harmonized_name="collection_date">missing</Attribute>
			<Attribute attribute_name="geo_loc_name" display_name="geographic location" harmonized_name="geo_loc_name">USA</Attribute>
			<Attribute attribute_name="lat_lon" display_name="latitude and longitude" harmonized_name="lat_lon">missing</Attribute>
			<Attribute attribute_name="host" display_name="host" harmonized_name="host">missing</Attribute>
			<Attribute attribute_name="host_disease" display_name="host disease" harmonized_name="host_disease">missing</Attribute>
		</Attributes>
		<Links>
			<Link label="PRJNA218110" target="bioproject" type="entrez">218110</Link>
		</Links>
		<Status status="live" when="2018-10-03T08:06:20.839"/>
	</BioSample>
</BioSampleSet>
```

I THINK that what the loader does is look for hte "is_primary" tag for the sample name, and, if it doesnt exist, it guesses.

So  it should be loaded in as SAMN10170505 because:	`<Id db="BioSample" is_primary="1">SAMN10170505</Id>`

**Comment by mboudet** [comment]
>Can you confirm bioproejct is ALWAYS in link? Or is it in Id when the bioproject links to a ncbi bioproject instead of an internal bioproject?

Well, at least in [Acer saccharum](https://www.ncbi.nlm.nih.gov/biosample/?term=SAMN04958045), it's not. It's not in anywhere in the xml actually, which is weird.

It might be in the ID field for some samples, I will keep looking.

>I THINK that what the loader does is look for hte "is_primary" tag for the sample name, and, if it doesnt exist, it guesses. (the latest t3 loader. the t2 loader just assumes its the second one in the array i think)

There is a function find_primary_ID in the V3 loader, but I'm not sure it is used.

```
    // Extract data from the xml string.
    $sample_accession = $biosample->Ids->Id[0];
    $unique_name = $biosample->Ids->Id[1];
    $sra_accession = $biosample->Ids->Id[2];
    $description = $biosample->Description->Title;
```

Plus in the Shigella file and Acer saccharum file, the primary_id is the BioSample accession, not the sample name.

Maybe we should look for the db and db_label tag? If the db tag is in ['BioSample', 'SRA', etc]..

**Comment by noahcaldwell7** [comment]
No updates in over a year, closing issue.
