### ISSUE TITLE
[Tripal3] Ending regex filter for Expression file not working

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal_analysis_expression#250]
Hello,

I'm looking at the code for the expression file loader. The user can use two regex, one for the start of the data, and one for the end.
 
Looking at the loop, it feels like the ending regex will be ignored if no starting regex was added : 
[Here](https://github.com/tripal/tripal_analysis_expression/blob/master/tripal_analysis_expression/includes/TripalImporter/tripal_expression_data_loader.inc#L636)

```
      if (preg_match('/' . $re_stop . '/', $line) and $re_stop) {
        $data_ln = 0;
      }
```
If the regex is triggered, $data_ln is set to 0. Normally, everything after, including this line, should be ignored.

But later : 
```
if ($data_ln == 1 or !$re_start) {

```
This part is triggered even if $data_ln is set to 0, as long as there are no starting regex. So the line will keep on being added.
Shouldn't the test for the ending regex just lead to a `break` statement?

(Also, we increment the number of features even when parsing the header. Is that intentional?)

```
        if ($mat_head == 0) {
          $num_features++;
          $mat_head = 1;
          continue;
        }
```

**Comment by almasaeed2010** [comment]
Sorry for the delay on this. I am not sure what this is for so I am gonna defer to @bradfordcondon on it.

**Comment by bradfordcondon** [comment]
i also don't understand the point of supplying a regexp for the start/end of the data, so i never touched this.

incrementing num_features in the headers is wrong, but also inconsequential because its just for reporting.

>Looking at the loop, it feels like the ending regex will be ignored if no starting regex was added :

this seems problematic.

@mboudet does it makes sense to you to provide a regexp start/end ?  If so i'd welcome a fix.  If not i'd just as soon not worry about it.

**Comment by mboudet** [comment]
@bradfordcondon No really. While it _might_ be useful in some edge cases, I feel like it's easier to just cleanup the input file beforehand.

Plus since it was not reported until now, I guess nobody uses it, since it would instantly fail. I only found out because I was porting the code.

**Comment by bradfordcondon** [comment]
I'd just remove it but its so embedded i the code its hard to remove... maybe we just remove the ending regexp from the input form?

**Comment by mboudet** [comment]
It would work. But it would take more work than just adding a _break_ statement.
It might also seems weird to keep the starting regex and not the ending.

**Comment by noahcaldwell7** [comment]
No updates in over a year, closing issue.
