### ISSUE TITLE
[Tripal V2] Url redirection issues in heatmap

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal_analysis_expression#252]
Hello,

In the feature heatmap, the Y axis is made of links to features. However, the link is built without accounting for an eventual custom base_url, leading to 404 errors.

[here](https://github.com/tripal/tripal_analysis_expression/blob/v7.x-2.x/includes/feature_heatmap_form.inc#L189)

It should be fixed by adding $GLOBAL['base_url'] in the url.

**Comment by almasaeed2010** [comment]
It probably needs to get the node_id instead and link directly to `node/nid`

**Comment by mboudet** [comment]
Fixed by #254
