### ISSUE TITLE
[Tripal V3] Jquery version?

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal_analysis_expression#255]
Hello,

In the expression.js file in the tripal_analysis_expression part, the jquery function $.on() function is used.
(Also in heatmap and heatmap-search). This function is only available starting from jquery 1.7, so it crash with the default version (1.4.4). 

Does this module require the  jquery_update module?

(It might be an error due to another of my modules, apologies if that's the case)

**Comment by almasaeed2010** [comment]
Hello @mboudet 

The module does indeed require jquery_update and we should add it as a dependency. Thanks for reporting!
