### ISSUE TITLE
Add ability to flag genes/transcripts as significantly associated with a treatment

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_analysis_expression#259]
This would take some thought. Easy enough to store the p-value and associated treatment (from pato?) in feature prop. Is it ok to link back to the original gene expression analysis or would we need a new analysis specifically describing the statistical test?

**Comment by bradfordcondon** [comment]
see previously closed issue:  https://github.com/tripal/tripal_analysis_expression/issues/48

**Comment by noahcaldwell7** [comment]
No updates in over a year, closing issue.
