### ISSUE TITLE
offer user a choice to update or ignore pvalue data

### ISSUE THREAD

**Issue by jwest60** [tripal/tripal_analysis_expression#272]
this issue refers to the importer for #48 

if data is being uploaded through the pvalue importer and a feature_cvterm already exists for that data, what do we do?

maybe we could give the user an option to either update or ignore, where update would cause the current data to be deleted from the database so the new data can take its place, and ignore would cause the importer to do nothing (other than inform the user that data already exists)

**Comment by bradfordcondon** [comment]
two scenarios:

User is uploading the same data and wants to update.

User is uploading different data from a different experiment.  User wants both sets of data.

In the second case you just need to use [the RANK field](https://laceysanderson.github.io/chado-docs/tables/feature_cvterm.html) so that the second experiment rank = 1 instead of 0.

**Comment by jwest60** [comment]
if the user is uploading the same data and wants to update, how do we know which set of data the user wants to update? should we provide the user with the ability to search through all existing data sets and select the one they want?

if the user is uploading different data, how do we determine what the rank needs to be? is it just a matter of checking to see if the exact same values exist in feature_cvterm and feature_cvtermprop at every rank until we find an empty one or is there a better way?

**Comment by bradfordcondon** [comment]
>if the user is uploading the same data and wants to update, how do we know which set of data the user wants to update?

Its tied to something like an analysis right? use that.

>if the user is uploading different data, how do we determine what the rank needs to be? is it just a matter of checking to see if the exact same values exist in feature_cvterm and feature_cvtermprop at every rank until we find an empty one or is there a better way?

Tripal has an API for associated features with CVTERM:  `chado_associate_cvterm()` [here](https://github.com/tripal/tripal/blob/4b46c43888059d2d5b21fcf05138f05d6053d9ea/tripal_chado/api/modules/tripal_chado.cv.api.inc#L1342)
  
I'd start there.

**Comment by jwest60** [comment]
for clarification, existing data is only updated when all the following criteria is met:
- a feature cvterm exists for the feature
- the analysis_id of the existing feature_cvtermprop matches the analysis_id given (i.e. the analyses are the same)
- the term_id of the existing feature_cvtermprop containing the evidence code matches the evidence code given (i.e. heat up needs to be differentiated from heat down)

otherwise a new feature cvterm is created, possibly with a different rank

if the user uploads a file where some of the features have existing feature cvterms and some of them dont, but the cvterm, evidence code, and analysis are all the same, how is that handled? do we update the existing entries and insert the non-existing ones or do we consider it new data entirely and create new feature cvterms with a different rank for all features?

**Comment by bradfordcondon** [comment]
the analysis ID should be the major guidepost.  If its the same analysis ID, then you're updating that analysis' set of annotations.

**Comment by jwest60** [comment]
fixed on #281 

for each feature in the csv, the importer now looks for a feature_cvterm with the same feature id and keyword, then looks for a feature_cvtermprop record containing the same analysis id and a feature_cvtermprop record containing the same evidence code. if all this information matches, then the pvalue record is updated for the feature_cvterm

if the record doesnt exist, or the information above doesnt match exactly, the importer looks for any feature_cvterms with the same feature id, gets the highest rank, and inserts the new records at a rank one higher

thanks for the help @bradfordcondon
