### ISSUE TITLE
Add new contributor

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal_analysis_expression#291]
This is to test if a new issue means building off master rather than adding a commit to a closed PR.

@allcontributors[bot] add @almasaeed2010 for code

**Comment by almasaeed2010** [comment]
Looks like I used the wrong bot lol

@all-contributors add @almasaeed2010 for code

**Comment by almasaeed2010** [comment]
Ok now that all conflicts have been resolved let's try adding someone else.

**Comment by almasaeed2010** [comment]
@all-contributors add @jwest60 for code

**Comment by almasaeed2010** [comment]
Ok let's try again

@all-contributors add @jwest60 for code

**Comment by bradfordcondon** [comment]
@all-contributors add @mboudet  for bug
