### ISSUE TITLE
Examples on Heatmap Form

### ISSUE THREAD

**Issue by martacds** [tripal/tripal_analysis_expression#298]
Is there a way to alter the examples for the Heatmap form once the module is installed?
![Capture15](https://user-images.githubusercontent.com/47527249/57856799-b1759500-77e5-11e9-930f-0a6c1ab07bc1.PNG)

I found them in the tripal_analysis_expression.install file but that only works if you alter it before installing it, right?

Thanks in advance!

**Comment by almasaeed2010** [comment]
Hi @marcsilvaitqb 

Settings for the module can be found at `admin/tripal/extension/tripal_analysis_expression/heatmap_settings`

Or by visiting Admin -> Tripal -> Extensions -> Expression Analysis

Thanks!

**Comment by marcsilvaitqb** [comment]
Thanks for the quick answer.

![Capture16](https://user-images.githubusercontent.com/47527249/57857755-ac194a00-77e7-11e9-8677-01e0cfcbbb95.PNG)

It doesn't show up on my extensions so I can't access it.

**Comment by almasaeed2010** [comment]
This is odd. It shows up on all of my sites. Can attempt pasting the URL?

**Comment by marcsilvaitqb** [comment]
Using the URL it shows a blank page with the message "You are not authorized to access this page. "

I have admin privileges in the page.

**Comment by almasaeed2010** [comment]
Thanks for testing! This means we didn't have the permissions setup correctly. I've pushed an update to fix this.

Could you please update the module then visit the people -> permissions and try to find "Edit tripal analysis expression settings"?

**Comment by almasaeed2010** [comment]
Note that you need to clear the cache in order for the permission to show up. To do so, simply run `drush cc all`.

**Comment by martacds** [comment]
Ok.
Just to check I update the module, then clean the cache, then go to People > permissions and find that option, right?

**Comment by almasaeed2010** [comment]
correct

**Comment by martacds** [comment]
I can't find that option in my permissions...

**Comment by almasaeed2010** [comment]
Looks like github rejected my update. My bad! I re-pushed the changes.

**Comment by martacds** [comment]
Found it! Thank you! Going to try again and I'll update.

**Comment by martacds** [comment]
I shows up in my Extensions and I can edit the example features!

Thank you so much :)

**Comment by almasaeed2010** [comment]
No problem! Thanks for reporting the issue!
