### ISSUE TITLE
Search Features tool

### ISSUE THREAD

**Issue by martacds** [tripal/tripal_analysis_expression#299]
Hi!

I think that the search tool on the heatmap block is not working properly for me. When I select one organism it immediately tells me "no results found" when I have 4 genes published. Selecting `any organism` and looking for either the identifier or the name of the genes also shows the same message of "no results found".
![Capture17](https://user-images.githubusercontent.com/47527249/57860596-0963ca00-77ed-11e9-9030-cd509001de4c.PNG)

Entering any one of those 4 genes in the heatmap form outputs the expected heatmap.

I'm looking to either fix it or remove it, either is fine, but of course I'd prefer to fix it.

Thank you!

**Comment by almasaeed2010** [comment]
I think this search is based on a materialized view that needs to be populated. 

The materialized view is called `expression_feature`. To populate it, you need to visit Tripal -> Data storage -> Chado -> Materialized Views. then find the mview and click the populate button.

This module also supports [Tripal Elasticsearch](https://github.com/tripal/tripal_elasticsearch), which would provide a much faster search.

**Comment by martacds** [comment]
Got it! Thank you!
