### ISSUE TITLE
HeatMap options don't show up on Extensions menu

### ISSUE THREAD

**Issue by martacds** [tripal/tripal_analysis_expression#300]
Hi, 
The option to edit the HeatMap examples doesn't show up in my Extensions menu. 
I had the same issue previously with a different clone of this website. The solution was to update the module and clear the cache, which I have done in this instance but the option still doesn't show up.
![Capture26](https://user-images.githubusercontent.com/47527249/58259373-4c351d00-7d6c-11e9-849c-de83599ef635.PNG)

I have also tried the link to the option directly, which tells me "You are not authorized to access this page. "

Thanks! And sorry to bother you with the same problem again.

**Comment by almasaeed2010** [comment]
Hello @martacds 

Sorry you are having trouble with the module. Could you please visit People -> Permissions and make sure that `Edit tripal analysis expression settings` exists?

Thanks!

**Comment by martacds** [comment]
Got it! The permission wasn't set right!
I have no ideia how that happened and to think of all the time I have spent trying to figure out what was going on haha.

Thank you so much!

**Comment by almasaeed2010** [comment]
It happens to me all the time 😆 

Glad you fixed it!
