### ISSUE TITLE
job crashes when uploading expression data

### ISSUE THREAD

**Issue by zhuyiqin** [tripal/tripal_analysis_expression#304]
I'm trying to upload my expression data using Expression Data Loader. I have created the analysis and my file format is matrix. But when I ran the job, it crashed every time as following:
![image](https://user-images.githubusercontent.com/33781684/61099251-40c0c100-a494-11e9-82bd-5e054a3adf50.png)

I wonder the reason of this issue and how to resolve it. Thanks!

**Comment by almasaeed2010** [comment]
Hello @zhuyiqin 

We are gonna need a little more information. Could you please share the matrix file you used? If the file is large, please trim it to have only a few entries (around 10 will be enough). Also, have loaded your sequences before adding expression data?

Sorry for the delay!

Thanks

**Comment by spficklin** [comment]
This issue is really old and hasn't been commented on so I'm going to close it out.
