### ISSUE TITLE
pvalue field does not display

### ISSUE THREAD

**Issue by jwest60** [tripal/tripal_analysis_expression#305]
this issue exists on branch `p-values` located [here](https://github.com/tripal/tripal_analysis_expression/tree/p-values)

the name of the field is `local__expression_details` and its supposed to show up for the mrna bundle

the field is populated with data and displays correctly when 'Hide empty fields' is unchecked but will not show up otherwise

its likely that tripal thinks the field is empty for some reason but im not sure why

**Comment by jwest60** [comment]
fixed

this is the code that's causing the field to be hidden (tripal/tripal.fields.api.inc, line 154)
```
  if (array_key_exists($delta, $items) and
    array_key_exists('value', $items[$delta]) and
    empty($items[$delta]['value'])) {
    return TRUE;
  }
```

basically `$entity->{$field}['und'][0]['value']` is empty, so tripal thinks the field is empty

i was storing the table data in `$entity->{$field}['und'][0]['pvalue_data'] instead and leaving value empty, and after moving the data from `pvalue_data` to the `value` key, everything works

**Comment by almasaeed2010** [comment]
Good catch! This has to be a bug in Tripal though. How it manage to get to the formatter if value wasn't set. It's supposed to use caching to determine whether to run the formatter. Could it be that the formatters are getting executed even though the field is actually removed from display? I'll need to go through the code to determine if that's the case. If it is, it would explain a lot about the site's slowness.
