### ISSUE TITLE
Expression Loading completes but doesn't do anything

### ISSUE THREAD

**Issue by martacds** [tripal/tripal_analysis_expression#309]
Hi!

I am trying to upload some expression data that I have uploaded before, just for a different analysis. When I run the job, the first and last messages are what I expected (the warning about rolling back if it fails, and the Done.) but in the middle it's just a space, whereas I was expecting a series of errors regarding the pseudogenes in my sequences (see: #295 ). Afterwads I have no expression.

I have already have the organism, the analysis and the biosamples loaded. I'm afraid it might be somehting silly but I just can't figure out what it is.

Thaks in advance!

UPDATE: Apparently the problem is just with the option Unique Name. I just tried with a different matrix that is organized by Name and it worked: the expression values were uploaded to my portal.

**Comment by jwest60** [comment]
Glad you got it fixed. We just merged a change that gives more clear logging information on the job page, so if the issue occurs again, you should be able to see what's happening with your job.

**Comment by martacds** [comment]
Well, I didn't really get it fixed, I just used a different type of file that wasn't ideal, unfortunately. But I will have to run it again, so hopefully the extra info will help. Thanks!

**Comment by martacds** [comment]
Hi again!
I just re-tried with the matrix set for unique name and got the error "Please make sure there is only one instance of each feature in the expression file." even though I know there are no duplicate entries.

What is happening?

Thak in advance

**Comment by martacds** [comment]
Figured it out! The file was accidentaly saved comma delimited. Closing this.
