### ISSUE TITLE
Download option not working

### ISSUE THREAD

**Issue by martacds** [tripal/tripal_analysis_expression#310]
I've been having some issues with the download options for the expression data. When I click on it, nothing happens and if I copy the link, it lands on an Access Denied page. Is this a permissions issue? What am I missing? Thanks in advance!

**Comment by almasaeed2010** [comment]
Hello @martacds,

Where have you experienced this issue (feature page, analysis, etc)? The module provides download options in multiple pages so it would be helpful to know which page is failing.

Thanks!

@jwest60 please look into this when you get a chance.

**Comment by martacds** [comment]
Hi @almasaeed2010 , 
Everywhere there is a download option, so in my portal that would be in the heatmap and the feature page (which is genes in my case).

Thanks

**Comment by jwest60** [comment]
Hi @martacds,

It looks like this was a permissions issue, and it also seems that permissions for downloading expression data weren't set up properly for this module. We just merged a change that will allow you to update permissions on your portal so you should now be able to give yourself the permissions needed to download data.

Additionally, to avoid confusion, the download link will no longer display if you don't have the necessary permissions.

Let us know if the problem persists. Thanks!

**Comment by martacds** [comment]
Hi @jwest60 !

I am so sorry it took me so long to answer but I ran into other problems that stopped me from checking this fix.
Everything works now! Thank you so much :)
