### ISSUE TITLE
Search by GO terms is not working

### ISSUE THREAD

**Issue by martacds** [tripal/tripal_analysis_expression#313]
Hi!
I cannot search by GO terms in my heatmap tool. I have InterPro information added to my portal and it seems to be in working order because it shows in the feature pages.

How can I fix this? Or alternatively remove the example from the Search Features field.

Thank you!

**Comment by almasaeed2010** [comment]
Hello @martacds 

The search relies on the materialized view `expression_feature`. Did populate the mview after loading InterPro/GO?

Thanks

**Comment by martacds** [comment]
Thanks for the answer @almasaeed2010 .

Yes, I have populated that view.

**Comment by almasaeed2010** [comment]
You can change the example value for the heatmap by visitng Tripal -> Extensions -> Expression Analysis -> Heatmap Settings (/admin/tripal/extension/tripal_analysis_expression/heatmap_settings). However, there isn't a way to change the example for the search field. What's possible is writing some code to use the form hook and changing the description there.

If possible, could you run the following SQL query to get an idea of what the content of the table looks like?

```sql
SELECT * FROM chado.expression_feature WHERE accession IS NOT NULL AND accession != '' LIMIT 3;
```

**Comment by martacds** [comment]
> What's possible is writing some code to use the form hook and changing the description there.
Alright I'll look into that, thanks.

That SQL query returns no results.

**Comment by almasaeed2010** [comment]
This means that there are no GO or InterPro terms associated with the features that have expression data. The feature pages that show InterPro terms, do they also show expression data? This search will only provide results if the feature has expression data.

**Comment by martacds** [comment]
>  The feature pages that show InterPro terms, do they also show expression data? 

Oh! I was under the impression that since the features with InterPro terms and the features with expression are related, that the module was able to make that connection.
I will have to figure out something different then and meanwhile remove those search options.

Thank you so much!
I might get back to you with some questions about that form hook :)

**Comment by almasaeed2010** [comment]
No problem. Anytime!
