### ISSUE TITLE
Error loading tsv and csv Biosamples

### ISSUE THREAD

**Issue by fernandoGarcia21** [tripal/tripal_analysis_expression#314]
Hello!

I am trying to upload my biosamples in TSV or CSV file through the uploading interface and I got the following error:

Notice: Undefined index: attributes in tripal_biomaterial_loader_v3->form() (line 111 of /var/www/html/sites/all/modules/tripal_analysis_expression/tripal_biomaterial/includes/TripalImporter/tripal_biomaterial_loader_v3.inc).
Notice: Undefined index: values in tripal_biomaterial_loader_v3->form() (line 112 of /var/www/html/sites/all/modules/tripal_analysis_expression/tripal_biomaterial/includes/TripalImporter/tripal_biomaterial_loader_v3.inc).
Warning: Invalid argument supplied for foreach() in tripal_biomaterial_loader_v3->form() (line 139 of /var/www/html/sites/all/modules/tripal_analysis_expression/tripal_biomaterial/includes/TripalImporter/tripal_biomaterial_loader_v3.inc).
Warning: Invalid argument supplied for foreach() in tripal_biomaterial_loader_v3->form() (line 147 of /var/www/html/sites/all/modules/tripal_analysis_expression/tripal_biomaterial/includes/TripalImporter/tripal_biomaterial_loader_v3.inc).

I have tryied this process by using the examples files of the documentation and the result has not been successful.

However, when I upload an xml file, the file is processed correctly.

Looking forward to your reply.

**Comment by bradfordcondon** [comment]
hi @fernandoGarcia21 we wont be able to help without your CSV/TSV file (just the first few lines are fine).  You'll want to compare it to our [example files](https://github.com/tripal/tripal_analysis_expression/blob/master/example_files/3175-biomaterial.csv)/doublecheck the [requirements](https://github.com/tripal/tripal_analysis_expression#loading-biosamples-from-a-flat-file)

**Comment by fernandoGarcia21** [comment]
@bradfordcondon thank you for your reply.

I am using the the example data in the documentation. For instance, I am using the 3175-biomaterial.csv, as can be seen in the following screenshot.

![image](https://user-images.githubusercontent.com/20094274/66178281-57dc0d00-e697-11e9-9e4a-b425c7542b87.png)

I performed a debug to the source code in the file **tripal_biomaterial_loader_v3.inc** and I printed the variable **$terms_to_check** which is used to build the CV terms form. .

![image](https://user-images.githubusercontent.com/20094274/66178486-23b51c00-e698-11e9-88ea-6aae526fab33.png)

I printed it after loading an xml file from NCBI and the CSV file that I downloaded from the example files (**3175-biomaterial.csv**) here the output considering both situations:

**Output by the XML input file:**

{
  "attributes": {
    "isolate": {
      "attribute_name": "isolate",
      "harmonized_name": "isolate",
      "display_name": "isolate"
    },
    "cultivar": {
      "attribute_name": "cultivar",
      "harmonized_name": "cultivar",
      "display_name": "cultivar"
    },
    "ecotype": {
      "attribute_name": "ecotype",
      "harmonized_name": "ecotype",
      "display_name": "ecotype"
    },
    "age": {
      "attribute_name": "age",
      "harmonized_name": "age",
      "display_name": "age"
    },
    "dev_stage": {
      "attribute_name": "dev_stage",
      "harmonized_name": "dev_stage",
      "display_name": "development stage"
    },
    "geo_loc_name": {
      "attribute_name": "geo_loc_name",
      "harmonized_name": "geo_loc_name",
      "display_name": "geographic location"
    },
    "tissue": {
      "attribute_name": "tissue",
      "harmonized_name": "tissue",
      "display_name": "tissue"
    },
    "Column to differentiate samples": {
      "attribute_name": "Column to differentiate samples"
    }
  },
  "values": [
    "not collected",
    "not collected",
    "not collected",
    "not collected",
    "not collected",
    "not collected",
    "not collected",
    "903"
  ]
}

**Output by the CSV input file:**

[
  {
    "attributes": "biomaterial_provider"
  },
  {
    "values": null
  },
  {
    "attributes": "cultivar"
  },
  {
    "values": null
  },
  {
    "attributes": "geo_loc_name"
  },
  {
    "values": null
  },
  {
    "attributes": "tissue"
  },
  {
    "values": null
  },
  {
    "attributes": "treatment"
  },
  {
    "values": null
  }
]

In the source code, the program wants to extract the list of "attributes" in order to create the CV term form like this:

![image](https://user-images.githubusercontent.com/20094274/66179243-c5d60380-e69a-11e9-8b5c-30c0e24beb48.png)


However, both lists, the "attributes" and "values" are null:
![image](https://user-images.githubusercontent.com/20094274/66179214-ac34bc00-e69a-11e9-8c71-3cdd038fe08a.png)


The program cannot find the list of attributes and it shows the following error message and the CV term form is not created:

![image](https://user-images.githubusercontent.com/20094274/66178885-77743500-e699-11e9-939a-b47d624c16d1.png)

Looking forward to your reply.

**Comment by bradfordcondon** [comment]
Looks like the cvterm assignment form isn't working for CSV files, its finding the attributes (the column names) but not the values (the row values for that column).  The biomaterials still load.   I'm sure we would welcome a fix for this.

Are you able to use a different format?  XML in particular should work.

**Comment by fernandoGarcia21** [comment]
Hello @bradfordcondon I have modified the source code in order to fix the already mentioned bug  and other as described next:

**

1. Change the validation isset into !empty

**

The value set by default in $values['file_local'], $values['file_upload'] and $values['file_upload_existing'] is NULL, so the isset will consider the statement as TRUE. 

![image](https://user-images.githubusercontent.com/20094274/66537822-7d17c200-eb54-11e9-928f-85623f0ef223.png)


**

2. Change the function to print the error log in the function test_biosample_cvterms_flat

**

When the flat file was not found in the server or when there are not samples in the flat file, the system prints an error message in the log, however when it attempts to call the function logMessage it generates the following error:

Error: Using $this when not in object context in test_biosample_cvterms_flat() (line 1039 of /var/www/html/sites/all/modules/tripal_analysis_expression/tripal_biomaterial/includes/TripalImporter/tripal_biomaterial_loader_v3.inc

![image](https://user-images.githubusercontent.com/20094274/66616988-acd2d280-ec05-11e9-963b-7d3dacbc832b.png)

To fix this bug I print the error message in the log by means of the function error_log instead of logMessage:

![image](https://user-images.githubusercontent.com/20094274/66617453-c117cf00-ec07-11e9-91a8-1b43b188a2c8.png)

**

3. Read the attributes and values of the flat file and set them into the attributes_list in a consistent format:

**

- Firstly I declared a variable to determine the number of the row containing the header: $nLineHeader
- The values in attribute list is initialized empty: $attribute_list["values"] = [];
- Set only one value "attributes" in the attributes list, which contains the unique headers:  $attribute_list["attributes"][$header] = $header;
- Fill the unique values into the attribute_list array from lines in the flat file, starting from the next line after the header: 

  $tmpNumLine = 0;
  while ($line = fgetcsv($fp, 0, $separator, $enclosure)) {
    $tmpNumLine++;
    if($tmpNumLine > $nLineHeader){
      $attribute_list["values"] = array_merge($attribute_list["values"], $line);
    }
  }
  $attribute_list["values"] = array_valuesarray_unique($attribute_list["values"]);

![image](https://user-images.githubusercontent.com/20094274/66617740-e78a3a00-ec08-11e9-84d9-7004f76fc737.png)

After applying these changes in the code, my TSV or CSV files are loedad correctly into the biosamples interface.

![image](https://user-images.githubusercontent.com/20094274/66618231-fb36a000-ec0a-11e9-9ebd-afb17a01b6fd.png)

Attached is the file tripal_biomaterial_loader_v3.inc 
[tripal_biomaterial_loader_v3.zip](https://github.com/tripal/tripal_analysis_expression/files/3715258/tripal_biomaterial_loader_v3.zip)
containing all the modifications I have described above.

**Comment by bradfordcondon** [comment]
hi @fernandoGarcia21  this would be much easier to review if you could submit your changes as a pull request.  This would not only benefit us making it easier to review (and to provide feedback), but would also give you credit for the work that you've done.

  To do that you would

- fork this repository on github
- push your changes to your fork,
- create a pull request from your fork to here [guide](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork)

Here is a [good guide[(https://gist.github.com/Chaser324/ce0505fbed06b947d962) for how forking works and all the necessary git comments.

**Comment by fernandoGarcia21** [comment]
Hello @bradfordcondon excuse me for late reply, I just created the pull request. 

Best regards.

**Comment by dsenalik** [comment]
I have submitted a couple of corrections to Fernando's pull request, as pull request #358

**Comment by spficklin** [comment]
I think this issue forgot to get closed as PR #358 is merged.  Closing.
