### ISSUE TITLE
Clickable cvterms on significant expression pane

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_analysis_expression#330]
On the "significant expression" pane, cvterms should be clickable to learn more about them and get other features annotated with those terms.

**Comment by almasaeed2010** [comment]
Let's have @noahcaldwell7 give this a try. I suggest we start by linking the terms to a page that retrieves the term's definition. We can later add more information into the page.

**Comment by noahcaldwell7** [comment]
Joe and I set up links to a basic info page. 
<img width="520" alt="Screen Shot 2020-01-23 at 8 57 09 AM" src="https://user-images.githubusercontent.com/50276746/72990587-6b35f400-3dbe-11ea-991d-9007ac3c77ea.png">
