### ISSUE TITLE
Add documentation about biosample selector (TSV) loader

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal_analysis_expression#353]
We want to have some documentation about how to load tsv files instead of xmls

**Comment by RaymondS1** [comment]
Getting TSV files from run selector

**Comment by RaymondS1** [comment]
1) Type specific organism ( make sure SRA is selected)

2) Narrow down search by selecting:
              a)  Proper source, DNA or RNA (on the left side)
              b)  Proper organism on the left side 
              c)  Platform, most likely illumina 
              d)  Any others, as needed
![image](https://user-images.githubusercontent.com/43583505/87336644-29d20600-c510-11ea-8c00-d87588a12e56.png)

**Comment by RaymondS1** [comment]
3) Select: Send to, then Run Selector 

![image](https://user-images.githubusercontent.com/43583505/87336786-669dfd00-c510-11ea-8171-86c83e3ce253.png)

4) Click metadata to download the csv flie 

  
![image](https://user-images.githubusercontent.com/43583505/87336991-b7adf100-c510-11ea-963a-4caabee6a2e2.png)

**Comment by mestato** [comment]
"If there are multiple sequencing runs associated with the same biosample that should be treated as independent biosamples, the XML loader will not work (it creates only one record). To get around this, follow these instructions: "

**Comment by almasaeed2010** [comment]
merged to readme/docs
