### ISSUE TITLE
Term local:expression_features does not exist in the database

### ISSUE THREAD

**Issue by martacds** [tripal/tripal_analysis_expression#368]
Hi!

I have recently created a new install of my genomic portal (so far it only has the modules, the static pages and BLAST databases) and I came across this warning message.
When checking for new fields in BLAST results, Genome annotation, Genome assembly and InterPro results:

`The term, local:expression_features, for the field, local__expression_features, does not exist in the database. The field instance cannot be added. Please make sure the term is correct and add it if necessary.`

I then tried to add it manually using _admin/tripal/loaders/chado_vocabs/chado_cvterms_ > Add Term, using expression_features as both name and accession, and local for the other 2 dropdown options. After I did that when I checked for new fields the following error message showed up several times at the top of the page:

`Notice: Undefined index: local__expression_features in tripal_create_bundle_fields() (line 844 of /var/www/html/drupal/web/sites/all/modules/contrib/tripal/tripal/api/tripal.entities.api.inc).`

I have checked my cvterm table and all the entries from the tripal_analysis_expression.fields.inc file that correspond to cvterms appear to have been added to that table without any issues. I'm just missing this one.

Because I am unsure of what exactly this field corresponds to I don't know at the moment if I can ignore this or if this a field that I am going to be needing down the line. I checked my previous portal and I also don't have a local__expression_features in these Tripal Content Types, so I might not need it.

Any help you can give me would be much appreciated!

Thank you, 
Marta

**Comment by almasaeed2010** [comment]
Looks like this field allows you to display a list of features that have expression data on the analysis page or the organism page. I am not sure why you are getting the warning since the term is automatically inserted when you click `check for new fields`. I believe it would be safe to ignore the warning if it's not causing pages to fail loading.

**Comment by martacds** [comment]
From the description it doesn't seem like something I would need, so I am going to consider this "solved".

But I just want to reiterate that it is not getting automatically added. All the other terms show up in the green message box and that is the only term with that message. It is therefore not showing up in my Manage Fields list.
I have checked both the chado.cvterm table and the list of cvterms for the local database and the expression_features cvterm does not exist in either. Might be something to do with my install but I don't get the difference in behaviour between the terms.

Thank you for the quick answer!

**Comment by almasaeed2010** [comment]
Thanks for reporting the issue @martacds. We will look into this issue as soon as we can.

**Comment by dsenalik** [comment]
I have encountered this exact problem.
However, I found the error, and have submitted pull request #370 to fix it.
