### ISSUE TITLE
Functional changes for loaders

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal_analysis_expression#424]
This is my placeholder for issues found in testing.

1. Expression data loader, when using matrix format, the header for the first column containing the feature_id currently has to be blank. _i.e._ This does not work
```
gene    samp1   samp2   samp3    samp4
xx01.mRNA        0       0       0       0
```
but this does
```
        samp1   samp2   samp3    samp4
xx01.mRNA        0       0       0       0
```
The culprit is a ```trim()``` statement, change to ```rtrim()``` https://github.com/tripal/tripal_analysis_expression/pull/425/commits/7fe9ee7482eff07ed2297c2de21be3e7770a008d

2. ```Invalid argument supplied for foreach() tripal_expression_data_loader.inc:670```
    This happens when there are no NCBI accession numbers. Simple to fix. https://github.com/tripal/tripal_analysis_expression/pull/425/commits/51fae22cd280452c50c0aabb02ea0948b512bdb7

3. ```[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "biomaterial_id" of relation "assay_biomaterial" violates not-null constraint```
    This happened with "Create Biosample Records" unchecked, because they are already loaded by the biomaterial loader, and names in expression file did not match those already loaded. Throw an exception if this happens, with a helpful error message. https://github.com/tripal/tripal_analysis_expression/pull/425/commits/ba21625b77d58a1c8af89b02e02e269dead8f2cb

4. Biomaterial loader is loading the header line of a biomaterial TSV file (biomaterial name created is "sample_id")
    File pointer has been reset at the point when samples are read, we just need to read and discard the first line. https://github.com/tripal/tripal_analysis_expression/pull/425/commits/861aa0d8d1885989b79957585b0b0d917080557d

5. ```WD php: Error: Call to a member function getValue() on null in tripal_expression_data_loader->getAssayName() (line 1507 of .../tripal_analysis_expression/tripal_analysis_expression/includes/TripalImporter/tripal_expression_data_loader.inc).```
    This appears to be a typo, ```$sample``` cannot be an array and an object at the same time. https://github.com/tripal/tripal_analysis_expression/pull/425/commits/557d5087c435b08bef375616b613000875fd1fe0
    
6. ```WD php: Error: Call to a member function getValue() on null in tripal_expression_data_loader->getAcquisitionName() (line 1742 of .../tripal_analysis_expression/tripal_analysis_expression/includes/TripalImporter/tripal_expression_data_loader.inc).```
    This is a duplicate of the error above in 5. https://github.com/tripal/tripal_analysis_expression/pull/425/commits/e79765972ceac6e43effafa5e04a8746bf33cbe0

7. Column files do not have header lines, matrix files do. It would be good to have a more explicit description of this in the loader screen.
    The variable ```public static $upload_description``` can be also used at the column vs. matrix radio button. https://github.com/tripal/tripal_analysis_expression/pull/425/commits/a4c5032b80d7a84ba0efb2c153b3b7b5b9ee16db

**Comment by spficklin** [comment]
Fixes as per PR #425
