### ISSUE TITLE
The  'tripal_analysis_expression features form for heatmap' block appears in every page after module installation

### ISSUE THREAD

**Issue by sdash-github** [tripal/tripal_analysis_expression#6]
After installing the module, the block 'tripal_analysis_expression features form for heatmap' appears at the bottom of every page. Ideally, it should appear in designated pages or after configured to become active.  

At present, we are using neither this form nor the heatmap generated after submitting gene IDs via this form.  I had to go via Drupal blocks to inactivate it at four different places to get rid of it appearing in every page of our site.

**Comment by almasaeed2010** [comment]
Hello @sdash-github 

Drupal provides a method to list the urls of pages where a block can appear. In the ```structure->blocks->(block name) configure``` page, you'll find visibility settings near the bottom. 
By selecting ```Only the listed pages ``` option, you can hide the block from all pages except the listed URLs. In case you needed to completely hide the block, simply remove it from the ```main content``` section by choosing ```- none -``` in the blocks page.

In the meantime, this is the best solution. We are working on an upgrade for the module that'll designate a configurable page for the form.

Thanks!

**Comment by sdash-github** [comment]
Abdullah.
Thanks for the prompt response. I had already achieved it through the Drupal block utilities. Glad to hear you would be addressing it when you upgrade the module.
Sudhansu
